name: CI/CD
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Setup JDK
        uses: actions/setup-java@v3.4.1
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Execute maven build
        run: mvn package
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: build-artifact
          path: target/*.jar